python train.py \
--data_name coco \
--cnn_type vgg19 \
--text_encoder gru \
--max_violation \
--vocab ./vocab \
--batch_size 75 \
--add_data \
--use_restval \
--logger_name runs/vgg19_adjs \
--learning_rate 2e-4 \
--margin 0.2