
python train.py \
--data_path datasets/ \
--data_name coco \
--adapt_data f30k \
--adapt_split train \
--adapt_batch_size 64 \
--val_data f30k \
--val_split val \
--cnn_type resnet152 \
--val_batch_size 128 \
--img_dim 2048 \
--logger_name runs/coco_f30k/default/ \
--text_encoder gru \
--max_violation \
--add_data \
--use_restval \
--consistency_weight 20. \
--lr_update 15 \
--vocab ./vocab \
--resume runs/resnet152_ft/checkpoint.pth.tar \
--finetune \
--workers 12 \
--learning_rate 1e-5 \
